# 회의록 처리 설정 파일
# 이 파일을 수정하여 입출력 경로와 모델 설정을 변경할 수 있습니다.

# Base Model 설정
base_model:
  # 사용할 모델 경로
  model_path: "Qwen/Qwen3-4B-AWQ"
  model_name: "Qwen3_4B"  # 출력 폴더명에 사용될 이름
  
  # 입출력 경로
  input_dir: "../Raw_Data_val"  # 입력 데이터 디렉토리
  output_dir: "../Pre_Training/4B_base_model_results"  # 출력 디렉토리
  
  # 청킹 설정
  chunk_size: 5000  # 텍스트 청킹 크기
  chunk_overlap: 512  # 청크 간 오버랩 크기
  
  # 모델 파라미터
  temperature: 0.2
  max_tokens: 2048
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.7
  max_model_len: 16384

# LoRA Model 설정
lora_model:
  # 모델 경로
  base_model_path: "Qwen/Qwen3-8B"
  lora_model_path: "qwen3_lora_ttalkkac_8b"  # LoRA 어댑터 경로
  merged_model_path: "8B_merged_qwen3_lora_model"  # 병합된 모델 저장 경로
  
  # 입출력 경로
  input_dir: "../Raw_Data_val"  # 입력 데이터 디렉토리
  output_dir: "8B_lora_model_results"  # 출력 디렉토리
  
  # 청킹 설정
  chunk_size: 5000
  chunk_overlap: 512
  
  # 모델 파라미터
  temperature: 0.3
  top_p: 0.9
  repetition_penalty: 1.1
  max_new_tokens: 2048
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_model_len: 8192
  
  # 테스트 설정
  test_file_limit: 0  # 0이면 전체 파일 처리, 양수면 해당 개수만 처리

# 유사도 평가 설정
similarity_evaluation:
  # Pre-training (학습 전) 평가 설정
  pre_training:
    # Gold 데이터 경로 (정답 데이터)
    gold_data_path: "../Gold_Standard_Ttalkkac"
    
    # 모델별 결과 경로
    results:
      "1.7B": "../Pre_Training/1.7B_base_model_results"
      "4B": "../Pre_Training/4B_base_model_results"
      "8B": "../Pre_Training/8B_base_model_results"
    
    # 출력 파일 설정
    output_dir: "./pre_similarity_results"
    output_prefix: "pretrain"  # 파일명 접두사
  
  # Post-training (학습 후) 평가 설정
  post_training:
    # Gold 데이터 경로 (정답 데이터)
    gold_data_path: "../Gold_Standard_Ttalkkac"
    
    # 모델별 결과 경로
    results:
      "1.7B": "../Post_Training/1.7B_lora_model_results"
      "4B": "../Post_Training/4B_lora_model_results"
      "8B": "../Post_Training/8B_lora_model_results"
    
    # 출력 파일 설정
    output_dir: "./post_similarity_results"
    output_prefix: "post"  # 파일명 접두사
  
  # 평가 파라미터
  evaluation_params:
    sample_size: 100  # 랜덤 샘플링 크기 (0이면 전체 파일 평가)
    random_seed: 42  # 재현 가능한 랜덤 샘플링을 위한 시드
    tfidf_max_features: 5000  # TF-IDF 최대 특징 수
    tfidf_ngram_range: [1, 2]  # N-gram 범위
    embedding_model: "text-embedding-3-large"  # OpenAI 임베딩 모델
    batch_size: 10  # 배치 처리 크기
    save_interval: 20  # 중간 저장 간격
    use_cache: true  # 임베딩 캐시 사용 여부

# 공통 설정
common:
  # 로깅 레벨
  log_level: "INFO"
  
  # 병렬 처리 설정 (현재는 순차 처리 권장)
  max_workers: 1
  
  # Hugging Face 토큰 (환경변수로도 설정 가능: HUGGINGFACE_TOKEN)
  huggingface_token: ""  # 빈 문자열이면 환경변수나 입력 프롬프트 사용
  
  # OpenAI API Key (환경변수로도 설정 가능: OPENAI_API_KEY)
  openai_api_key: ""  # 빈 문자열이면 환경변수 사용